export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCES'
export const GET_CLICKED_CHARACTER = 'GET_CLICKED_CHARACTER'
export const GET_SEARCH_TERM = 'GET_SEARCH_TERM'
export const GET_FILTER = 'GET_FILTER'